package com.henriquebecker.geocoordenadas;


public enum MapState {
    PLACING_MARKER, PLACING_CIRCLE_CENTER, PLACING_CIRCLE_END, PLACING_POLYGON_1, PLACING_POLYGON_2,
    PLACING_POLYGON_3, PLACING_POLYLINE_1, PLACING_POLYLINE_2, IDLE, REMOVING
}
